import { vi } from "vitest";
import type { EmulatorState } from "@/lib/emulator/use-emulator";

/**
 * One emulator hub stand-in for every playground suite, typed against the real
 * EmulatorState so a missing field or a mistyped override fails to compile.
 * Defaults: a loaded machine, nothing assembled or run, and each view a field
 * gates (d registers, external-call card, memory jump list) on its fallback.
 * Mocks are built per call so two hubs in one test never share call records.
 * Async fields resolve their real shape: an assemble resolving undefined would
 * let a suite pass on a branch the real hub never takes.
 */
export function makeHub(overrides: Partial<EmulatorState> = {}): EmulatorState {
  return {
    isLoaded: true,
    loadError: null,
    registers: Array(31).fill("0x0000000000000000") as string[],
    fpRegisters: [],
    vectorRegisters: [],
    sp: "0x0000000080000000",
    pc: 0x400000,
    nzcv: 0,
    changedRegs: new Set<number>(),
    changedFpRegs: new Set<number>(),
    isRunning: false,
    isAssembling: false,
    isHalted: false,
    programLoaded: false,
    error: null,
    assemblyErrors: [],
    breakpoints: new Set<number>(),
    droppedBreakpoints: [],
    currentLine: null,
    externalCall: null,
    instructions: [],
    codeBase: 0x400000,
    memoryRegions: [],
    stdout: "",
    stderr: "",
    notes: [],
    blocked: false,
    wantsTerminal: false,
    setOutputTap: vi.fn(),
    exitCode: null,
    hostedMode: false,
    vfsFiles: [],
    assemble: vi.fn(async () => true),
    assembleForTool: vi.fn(async () => ({
      success: true,
      error: null,
      errorLine: null,
    })),
    step: vi.fn(),
    stepBack: vi.fn(),
    canStepBack: false,
    stepCount: 0,
    savedStates: [],
    saveState: vi.fn(),
    loadState: vi.fn(),
    deleteState: vi.fn(),
    run: vi.fn(),
    pause: vi.fn(),
    reset: vi.fn(),
    toggleBreakpoint: vi.fn(),
    clearAllBreakpoints: vi.fn(),
    remapBreakpoints: vi.fn(),
    getMemory: vi.fn(() => new Uint8Array()),
    getMemoryMapped: vi.fn(() => true),
    readMemory: vi.fn(async (_addr: number, len: number) => new Uint8Array(len)),
    pushStdin: vi.fn(),
    stdinGiven: vi.fn(() => ""),
    resumeAfterInput: vi.fn(),
    setSnapshotsPaused: vi.fn(),
    closeStdin: vi.fn(),
    uploadVfsFile: vi.fn(),
    readVfsFile: vi.fn(async () => new Uint8Array()),
    deleteVfsFile: vi.fn(async () => true),
    resolveLabel: vi.fn(async () => null),
    lint: vi.fn(async () => []),
    m4Expand: vi.fn(async () => null),
    setBreakpointAddress: vi.fn(async () => {}),
    clearBreakpointAddress: vi.fn(async () => {}),
    restoreBookmark: vi.fn(async () => ({ success: true, stepped: 0 })),
    clearConsole: vi.fn(),
    dirtyAddrs: [],
    replayFrames: [],
    seekReplay: vi.fn(),
    ...overrides,
  };
}
