/**
 * Short hover-card content for every instruction the playground
 * understands, written in the cpsc 355 course voice. Monaco's hover
 * provider looks these up by upper-cased mnemonic; condition-code
 * variants (`B.EQ`, `B.NE`, ...) collapse onto the `B.cond` entry.
 */
export interface InstructionDoc {
  /** Short one-line summary. */
  summary: string;
  /** Optional longer notes; markdown-safe lines. */
  details?: string[];
  /** Brief example. */
  example?: string;
  /** Optional one-line C equivalent for students translating between
   *  asm and C. Operand names are placeholders (`Rd`, `Rn`, `op2`,
   *  `off`, etc.); the hover surfaces this verbatim. */
  cExample?: string;
  /** True when the mnemonic exists in ARMv8 but this emulator doesn't
   *  implement it; hover shows "not implemented" instead. */
  notImplemented?: boolean;
}

const BCOND_NOTE =
  "Conditional branch. NZCV set by an earlier `CMP`/`SUBS`/`ADDS`/`ANDS`/`TST`.";

export const INSTRUCTION_DOCS: Record<string, InstructionDoc> = {
  MOV: {
    summary: "Copy register or wide immediate into Rd.",
    details: [
      "`MOV Rd, Rm` is `ORR Rd, ZR, Rm`.",
      "`MOV Rd, #imm` auto-picks a MOVZ with the right `LSL` shift when the immediate fits one halfword.",
      "`MOV Xd, SP` / `MOV SP, Xn` lower to `ADD ..., #0`.",
    ],
    example: "mov x0, #42",
    cExample: "Rd = Rm; // or Rd = imm;",
  },
  MOVZ: {
    summary: "Move wide zero-extended; writes `imm << hw*16`, zeros the rest.",
    example: "movz x0, #0x1234, lsl #16",
    cExample: "Rd = imm << (hw * 16);",
  },
  MOVK: {
    summary: "Move wide, keep. Writes `imm << hw*16` but preserves the other halfwords.",
    example: "movk x0, #0xcafe, lsl #32",
    cExample: "Rd = (Rd & ~(0xffffULL << (hw * 16))) | (imm << (hw * 16));",
  },
  MOVN: { summary: "Move wide bitwise-NOT of immediate.", example: "movn x0, #0", cExample: "Rd = ~(imm << (hw * 16));" },
  ADD: { summary: "Rd = Rn + Rm/imm. No flags.", example: "add x0, x1, x2", cExample: "Rd = Rn + op2;" },
  ADDS: { summary: "Rd = Rn + Rm/imm, sets NZCV.", cExample: "Rd = Rn + op2; // NZCV updated" },
  SUB: { summary: "Rd = Rn - Rm/imm. No flags.", cExample: "Rd = Rn - op2;" },
  SUBS: { summary: "Rd = Rn - Rm/imm, sets NZCV (the basis of `CMP`).", cExample: "Rd = Rn - op2; // NZCV updated" },
  CCMP: {
    summary: "Compare only when cond holds; otherwise write the literal flags.",
    details: [
      "The taken path sets NZCV from `Rn - Rm` exactly as `CMP` does.",
      "The other path WRITES the 4-bit literal (`N Z C V`, high bit first), it does not leave the old flags alone.",
      "GCC builds `&&` and `||` chains out of these instead of branching.",
    ],
    example: "ccmp w1, 2, 0, eq",
    cExample: "// a == 1 && b == 2, without a branch",
  },
  CCMN: {
    summary: "The `CMN` form of `CCMP`: the taken path sets NZCV from Rn + Rm.",
    example: "ccmn w1, 3, 0, eq",
  },
  SMADDL: {
    summary: "Xd = Xa + Wn * Wm, the 32x32 product widened as signed.",
    details: ["The accumulator is a full 64-bit register; only the two sources are 32-bit.", "`SMULL` is this with `Xa = XZR`."],
    example: "smaddl x0, w1, w2, x3",
    cExample: "Xd = Xa + (long)Wn * (long)Wm;",
  },
  SMSUBL: { summary: "Xd = Xa - Wn * Wm, signed and widening.", example: "smsubl x0, w1, w2, x3" },
  UMADDL: { summary: "Xd = Xa + Wn * Wm, the sources read unsigned.", example: "umaddl x0, w1, w2, x3" },
  UMSUBL: { summary: "Xd = Xa - Wn * Wm, the sources read unsigned.", example: "umsubl x0, w1, w2, x3" },
  SMNEGL: {
    summary: "Xd = -(Wn * Wm), signed and widening.",
    details: ["Alias for `SMSUBL Xd, Wn, Wm, XZR`."],
    example: "smnegl x0, w1, w2",
  },
  UMNEGL: { summary: "Xd = -(Wn * Wm) with the sources read unsigned, wrapping at 64 bits.", example: "umnegl x0, w1, w2" },
  CLZ: {
    summary: "Rd = the number of leading zero bits in Rn.",
    details: ["Of zero it is the register width (64 for X, 32 for W), not an error."],
    example: "clz x0, x1",
    cExample: "Rd = __builtin_clzl(Rn); // 64 for Rn == 0",
  },
  CLS: {
    summary: "Rd = the number of leading bits matching the top bit, minus that bit.",
    details: ["Of 0 and of -1 alike it is the width minus one: 63 at X width, 31 at W."],
    example: "cls x0, x1",
  },
  RBIT: { summary: "Rd = Rn with its bit order reversed across the whole register.", example: "rbit x0, x1" },
  REV: {
    summary: "Rd = Rn with its byte order reversed (a byte-swap).",
    details: ["The X and W forms are different encodings, not one instruction with a width bit."],
    example: "rev x0, x1",
    cExample: "Rd = __builtin_bswap64(Rn);",
  },
  REV16: { summary: "Reverse the bytes inside each 16-bit halfword of Rn.", example: "rev16 x0, x1" },
  REV32: {
    summary: "Reverse the bytes inside each 32-bit word of Rn. X registers only.",
    details: ["There is no `REV32 Wd, Wn`: the W-sized byte-swap is `REV Wd, Wn`."],
    example: "rev32 x0, x1",
  },
  ADC: {
    summary: "Rd = Rn + Rm + C. No flags.",
    details: ["Register form only; AArch64 has no add-with-carry immediate. It follows an `ADDS` to carry one 64-bit word into the next."],
    example: "adc x0, x1, x2",
    cExample: "Rd = Rn + Rm + carry;",
  },
  ADCS: { summary: "Rd = Rn + Rm + C, sets NZCV.", example: "adcs w3, w4, w5", cExample: "Rd = Rn + Rm + carry; // NZCV updated" },
  SBC: {
    summary: "Rd = Rn - Rm - (1 - C). No flags.",
    details: ["The carry is the not-borrow an earlier `SUBS` left, so C = 1 means no borrow. Register form only."],
    example: "sbc x9, x10, x11",
    cExample: "Rd = Rn - Rm - (1 - carry);",
  },
  SBCS: { summary: "Rd = Rn - Rm - (1 - C), sets NZCV.", example: "sbcs w0, w1, w2", cExample: "Rd = Rn - Rm - (1 - carry); // NZCV updated" },
  AND: { summary: "Bitwise AND; register or bitmask immediate.", cExample: "Rd = Rn & op2;" },
  ANDS: { summary: "Bitwise AND with flag update (the basis of `TST`).", cExample: "Rd = Rn & op2; // NZCV updated" },
  ORR: { summary: "Bitwise OR; register or bitmask immediate.", cExample: "Rd = Rn | op2;" },
  EOR: { summary: "Bitwise XOR; register or bitmask immediate.", cExample: "Rd = Rn ^ op2;" },
  BIC: {
    summary: "Bit clear: Rd = Rn & ~Rm.",
    details: ["Register form only; AArch64 has no BIC-immediate. Clear a constant mask with `AND` and the inverted bits instead."],
    example: "bic w19, w20, w21",
    cExample: "Rd = Rn & ~Rm;",
  },
  LSL: { summary: "Logical shift left (Rd = Rn << amount).", cExample: "Rd = Rn << amt;" },
  LSR: { summary: "Logical shift right (unsigned).", cExample: "Rd = (unsigned)Rn >> amt;" },
  ASR: { summary: "Arithmetic shift right (sign-extending).", cExample: "Rd = (int)Rn >> amt;" },
  ROR: { summary: "Rotate right: bits leaving the bottom re-enter at the top.", cExample: "Rd = (Rn >> amt) | (Rn << (64 - amt));" },
  SBFX: { summary: "Extract a bitfield and sign-extend it.", cExample: "Rd = (int64_t)(Rn << (63 - (lsb + width - 1))) >> (64 - width);" },
  UBFX: {
    summary: "Unsigned bitfield extract: Rd = (Rn >> lsb) & ((1 << width) - 1).",
    details: ["Pulls `width` bits starting at `lsb` down to bit 0 and zeros the rest. The pattern for unpacking flag fields."],
    example: "ubfx w19, w20, #4, #4",
    cExample: "Rd = (Rn >> lsb) & ((1u << width) - 1);",
  },
  BFI: {
    summary: "Bitfield insert: low `width` bits of Rn land in Rd at `lsb`; other Rd bits survive.",
    details: ["The write is a merge, not a replace, so Rd keeps everything outside the field. UBFX is the matching read."],
    example: "bfi w19, w20, #8, #4",
    cExample: "Rd = (Rd & ~(mask << lsb)) | ((Rn & mask) << lsb);",
  },
  BFXIL: {
    summary: "Bitfield extract and insert low: the field lands at bit 0 of Rd, the rest of Rd survives.",
    details: ["Same `immr`/`imms` as `UBFX`; the difference is that `UBFX` zeroes everything outside the field and `BFXIL` leaves it."],
    example: "bfxil x0, x1, #8, #8",
    cExample: "Rd = (Rd & ~mask) | ((Rn >> lsb) & mask);",
  },
  UBFIZ: {
    summary: "Unsigned bitfield insert in zeros: the low `width` bits of Rn land at `lsb`, the rest of Rd is zeroed.",
    details: ["The inverse shape of `UBFX`. It is a plain write, not a merge: nothing of the old Rd survives."],
    example: "ubfiz x2, x1, #2, #32",
    cExample: "Rd = (unsigned long)(Rn & mask) << lsb;",
  },
  SBFIZ: {
    summary: "Signed bitfield insert: the same placement, sign-extended from the field's top bit.",
    example: "sbfiz x0, x1, #2, #30",
    cExample: "Rd = (long)(Rn & mask) << lsb; // sign filled above the field",
  },
  SXTB: { summary: "Sign-extend a byte to Wd/Xd (alias for `SBFM`).", example: "sxtb w0, w1", cExample: "Rd = (signed char)Rn;" },
  SXTH: { summary: "Sign-extend a halfword to Wd/Xd.", example: "sxth w0, w1", cExample: "Rd = (short)Rn;" },
  SXTW: { summary: "Sign-extend a word to 64-bit Xd.", example: "sxtw x0, w1", cExample: "Xd = (long)(int)Wn;" },
  UXTB: { summary: "Zero-extend a byte into Wd (alias for `UBFM`).", example: "uxtb w0, w1", cExample: "Rd = (unsigned char)Rn;" },
  UXTH: { summary: "Zero-extend a halfword into Wd.", example: "uxth w0, w1", cExample: "Rd = (unsigned short)Rn;" },
  UXTW: {
    summary: "Zero-extend a word into Xd.",
    details: ["GAS assembles it as `MOV Wd, Wn`: a W-register write clears the top half, so no separate bitfield word is needed. The counterpart of `SXTW`."],
    example: "uxtw x0, w1",
    cExample: "Xd = (unsigned long)(unsigned int)Wn;",
  },
  MUL: { summary: "Rd = Rn * Rm. Low bits only.", cExample: "Rd = Rn * Rm;" },
  MADD: { summary: "Rd = Ra + Rn * Rm.", cExample: "Rd = Ra + Rn * Rm;" },
  MSUB: { summary: "Rd = Ra - Rn * Rm.", cExample: "Rd = Ra - Rn * Rm;" },
  MNEG: {
    summary: "Rd = -(Rn * Rm). Alias for `MSUB Rd, Rn, Rm, ZR`.",
    example: "mneg x0, x1, x2",
    cExample: "Rd = -(Rn * Rm);",
  },
  SMULL: { summary: "Xd = Wn * Wm, the exact 64-bit product of two signed 32-bit values.", example: "smull x0, w1, w2", cExample: "long d = (long)a * b;" },
  UMULL: { summary: "Xd = Wn * Wm, the exact 64-bit product of two unsigned 32-bit values.", example: "umull x0, w1, w2", cExample: "unsigned long d = (unsigned long)a * b;" },
  SMULH: { summary: "Xd = the top 64 bits of the signed 128-bit product Xn * Xm.", example: "smulh x0, x1, x2", cExample: "Rd = (long)(((__int128)a * b) >> 64);" },
  UMULH: { summary: "Xd = the top 64 bits of the unsigned 128-bit product Xn * Xm.", example: "umulh x0, x1, x2", cExample: "Rd = (unsigned long)(((unsigned __int128)a * b) >> 64);" },
  UDIV: { summary: "Unsigned divide; divide-by-zero writes 0.", cExample: "Rd = (unsigned)Rn / (unsigned)Rm;" },
  SDIV: { summary: "Signed divide; divide-by-zero writes 0.", cExample: "Rd = (int)Rn / (int)Rm;" },
  NEG: { summary: "Rd = -Rn (alias for `SUB Rd, ZR, Rn`).", cExample: "Rd = -Rn;" },
  NEGS: { summary: "Rd = -Rn and sets NZCV (alias for `SUBS Rd, ZR, Rn`).", example: "negs x0, x1", cExample: "Rd = -Rn; // flags from 0 - Rn" },
  MVN: { summary: "Rd = ~Rn (alias for `ORN Rd, ZR, Rn`).", cExample: "Rd = ~Rn;" },
  ORN: {
    summary: "Rd = Rn | ~Rm. Logical OR with the second source inverted.",
    details: ["`MVN Rd, Rm` is this instruction with `XZR` as Rn."],
    example: "orn x0, x1, x2",
    cExample: "Rd = Rn | ~Rm;",
  },
  EON: {
    summary: "Rd = Rn ^ ~Rm, which is XNOR.",
    example: "eon x0, x1, x2",
    cExample: "Rd = ~(Rn ^ Rm);",
  },
  CMP: { summary: "`SUBS ZR, Rn, op2`. Sets NZCV, discards result.", cExample: "// (Rn - op2) sets NZCV" },
  CMN: { summary: "`ADDS ZR, Rn, op2`. Sets NZCV.", cExample: "// (Rn + op2) sets NZCV" },
  TST: { summary: "`ANDS ZR, Rn, op2`. Sets NZCV; accepts bitmask immediates.", cExample: "// (Rn & op2) sets NZCV" },
  CSEL: { summary: "Rd = cond ? Rn : Rm.", example: "csel x0, x1, x2, eq", cExample: "Rd = cond ? Rn : Rm;" },
  CSINC: { summary: "Rd = cond ? Rn : Rm+1. Basis of `CSET`.", cExample: "Rd = cond ? Rn : Rm + 1;" },
  CSINV: { summary: "Rd = cond ? Rn : ~Rm.", example: "csinv x0, x1, x2, eq", cExample: "Rd = cond ? Rn : ~Rm;" },
  CSNEG: { summary: "Rd = cond ? Rn : -Rm. How gcc spells abs().", example: "csneg x0, x1, x2, pl", cExample: "Rd = cond ? Rn : -Rm;" },
  CSET: { summary: "Rd = cond ? 1 : 0 (pseudo for `CSINC Rd, ZR, ZR, cond-inv`).", cExample: "Rd = cond ? 1 : 0;" },
  CSETM: { summary: "Rd = cond ? all-ones : 0 (pseudo for `CSINV Rd, ZR, ZR, cond-inv`).", example: "csetm w0, eq", cExample: "Rd = cond ? -1 : 0;" },
  CINC: { summary: "Rd = cond ? Rn+1 : Rn.", example: "cinc w2, w1, eq", cExample: "Rd = cond ? Rn + 1 : Rn;" },
  CINV: { summary: "Rd = cond ? ~Rn : Rn.", example: "cinv x0, x1, ne", cExample: "Rd = cond ? ~Rn : Rn;" },
  CNEG: { summary: "Rd = cond ? -Rn : Rn.", example: "cneg x0, x1, lt", cExample: "Rd = cond ? -Rn : Rn;" },
  LDR: {
    summary: "Load from memory. Picks 32-vs-64 bit based on Wt/Xt.",
    details: [
      "Addressing: immediate offset `[Xn, #imm]`, pre-index `[Xn, #imm]!`, post-index `[Xn], #imm`, register offset `[Xn, Xm]`, extended `[Xn, Wm, SXTW #k]`.",
      "`LDR Dt, [...]` reads an IEEE 754 double into the FP bank.",
      "`LDR Xt, =label` loads the label's address via a PC-relative literal pool.",
    ],
    cExample: "Rd = *(int*)(Rn + off);",
  },
  STR: { summary: "Store to memory. Same addressing modes as LDR.", cExample: "*(int*)(Rn + off) = Rd;" },
  LDRB: { summary: "Load byte into Wt.", cExample: "Rd = *(unsigned char*)(Rn + off);" },
  STRB: { summary: "Store low byte of Wt.", cExample: "*(unsigned char*)(Rn + off) = (unsigned char)Rd;" },
  LDRH: { summary: "Load halfword into Wt.", cExample: "Rd = *(unsigned short*)(Rn + off);" },
  STRH: { summary: "Store low halfword of Wt.", cExample: "*(unsigned short*)(Rn + off) = (unsigned short)Rd;" },
  LDRSB: {
    summary: "Load byte, sign-extend to Wt or Xt.",
    details: ["Takes the same pre/post-index writeback and unscaled negative offsets as `LDR`."],
    cExample: "Rd = *(signed char*)(Rn + off);",
  },
  LDRSH: {
    summary: "Load halfword, sign-extend to Wt or Xt.",
    details: ["Takes the same pre/post-index writeback and unscaled negative offsets as `LDR`."],
    cExample: "Rd = *(short*)(Rn + off);",
  },
  LDRSW: {
    summary: "Load word, sign-extend to Xt.",
    details: ["Takes the same pre/post-index writeback and unscaled negative offsets as `LDR`. GCC walks an int array with `ldrsw x0, [x1], 4`."],
    cExample: "Rd = *(int*)(Rn + off);",
  },
  LDP: {
    summary: "Load pair: `LDP Xt1, Xt2, [Xn, #imm]`, or the FP file with D/S registers.",
    details: ["Offset is scaled by register size (8 for X and D, 4 for W and S)."],
    cExample: "Rt1 = *(long*)(Rn + off); Rt2 = *(long*)(Rn + off + 8);",
  },
  STP: { summary: "Store pair; mirrors LDP (D/S pairs reach the FP file).", cExample: "*(long*)(Rn + off) = Rt1; *(long*)(Rn + off + 8) = Rt2;" },
  ADR: {
    summary: "PC-relative byte address of a label into Xd.",
    example: "adr x0, label",
    cExample: "Rd = &label;",
  },
  ADRP: {
    summary: "Address of the 4 KiB page that contains a label.",
    details: ["Pair with `add Xd, Xd, :lo12:label` to add the low 12 bits and reach the exact address."],
    example: "adrp x0, msg\nadd x0, x0, :lo12:msg",
  },
  B: { summary: "Unconditional branch to label (±128 MiB).", cExample: "goto label;" },
  BL: {
    summary: "Branch with link; writes return address to X30.",
    details: [
      "When the target is a host stub the linker rewrites this to hop through a trampoline in .text so the imm26 offset stays in range.",
    ],
    cExample: "label(); // X30 = return address",
  },
  BR: { summary: "Branch to address in Xn.", cExample: "goto *(void*)Xn;" },
  BLR: { summary: "BR with link (X30 := PC + 4 before jump).", cExample: "((void(*)())Xn)(); // X30 = return address" },
  RET: { summary: "Return; jumps to Xn (default X30). Halts when X30 is the `__main_return` sentinel.", cExample: "return;" },
  "B.COND": {
    summary: "Conditional branch (write as `B.EQ`, `B.NE`, `B.LT`, ...).",
    details: [BCOND_NOTE],
    example: "cmp w0, #0\nb.eq done",
    cExample: "if (cond) goto label;",
  },
  CBZ: { summary: "Compare-and-branch if register is zero.", cExample: "if (Rn == 0) goto label;" },
  CBNZ: { summary: "Compare-and-branch if register is non-zero.", cExample: "if (Rn != 0) goto label;" },
  TBZ: { summary: "Test-bit-and-branch if bit is clear.", example: "tbz w0, #0, even", cExample: "if (((Rn >> bit) & 1) == 0) goto label;" },
  TBNZ: { summary: "Test-bit-and-branch if bit is set.", cExample: "if (((Rn >> bit) & 1) != 0) goto label;" },
  SVC: {
    summary: "Supervisor call. With `#0` dispatches on `x8`.",
    details: [
      "Hosted syscall numbers: 63 read, 64 write, 93 exit, 56 openat, 57 close, 62 lseek.",
      "`SVC #N` with `N != 0` halts the CPU.",
    ],
  },
  NOP: { summary: "Do nothing; PC advances." },
  FMOV: {
    summary: "Copy bits: FP to FP, between the register files, or an 8-bit float immediate.",
    details: [
      "`FMOV Dd, Xn` / `FMOV Xd, Dn` (and the S/W pair) move raw bits between the files with no conversion; use `scvtf`/`fcvtzs` to convert a value.",
      "`FMOV Dd, #imm` / `FMOV Sd, #imm` takes a small power-of-two multiple of 1.0-1.9375 (0.5, 1.0, 2.0, 5.0, 9.0 all fit).",
      "Values outside that set (0.0, 0.1, 100.0) do not encode; load them from a `.double` / `.float` instead.",
    ],
    example: "fmov d9, 5.0",
  },
  FADD: { summary: "Fd = Fn + Fm; the register width picks single (`Sd`) or double (`Dd`)." },
  FSUB: { summary: "Fd = Fn - Fm (S or D form)." },
  FMUL: { summary: "Fd = Fn * Fm (S or D form)." },
  FDIV: { summary: "Fd = Fn / Fm (S or D form)." },
  FNMUL: {
    summary: "Fd = -(Fn * Fm): the sign flips AFTER the multiply.",
    details: ["Not the same as negating an operand: `fnmul` of `+0.0` and `3.0` is `-0.0`."],
    example: "fnmul d0, d1, d2",
    cExample: "Fd = -(Fn * Fm);",
  },
  FMADD: {
    summary: "Fused multiply-add: Fd = Fa + Fn * Fm. The accumulator is the LAST operand.",
    details: [
      "Fused means one rounding, so it is not `fmul` followed by `fadd`.",
      "`fmadd d4, d1, d2, d3` is `d3 + d1*d2`, never `d1 + d2*d3`.",
    ],
    example: "fmadd d0, d1, d2, d3",
    cExample: "Fd = fma(Fn, Fm, Fa);",
  },
  FMSUB: { summary: "Fd = Fa - Fn * Fm (the product is subtracted FROM the accumulator).", example: "fmsub d0, d1, d2, d3", cExample: "Fd = fma(-Fn, Fm, Fa);" },
  FNMADD: { summary: "Fd = -Fa - Fn * Fm.", example: "fnmadd d0, d1, d2, d3", cExample: "Fd = -fma(Fn, Fm, Fa);" },
  FNMSUB: { summary: "Fd = -Fa + Fn * Fm.", example: "fnmsub d0, d1, d2, d3", cExample: "Fd = fma(Fn, Fm, -Fa);" },
  FMAX: {
    summary: "Fd = the larger of Fn and Fm (S or D form).",
    details: ["A NaN operand makes the result NaN; `FMAXNM` ignores it instead.", "`fmax(+0.0, -0.0)` is `+0.0` in either operand order."],
    example: "fmax d0, d1, d2",
  },
  FMIN: {
    summary: "Fd = the smaller of Fn and Fm (S or D form).",
    details: ["Same NaN rule as `FMAX`; `fmin(+0.0, -0.0)` is `-0.0`."],
    example: "fmin d0, d1, d2",
  },
  FMAXNM: {
    summary: "IEEE maxNum: a NaN operand is ignored and the number wins.",
    details: ["This is what C's `fmax()` compiles to; `FMAX` propagates the NaN."],
    example: "fmaxnm d0, d1, d2",
    cExample: "Fd = fmax(Fn, Fm);",
  },
  FMINNM: {
    summary: "IEEE minNum: a NaN operand is ignored and the number wins.",
    example: "fminnm d0, d1, d2",
    cExample: "Fd = fmin(Fn, Fm);",
  },
  FNEG: {
    summary: "Fd = -Fn (flips the sign bit; S or D form).",
    example: "fneg d16, d16",
    cExample: "Dd = -Dn;",
  },
  FABS: {
    summary: "Fd = fabs(Fn) (clears the sign bit; S or D form).",
    example: "fabs d0, d1",
    cExample: "Dd = fabs(Dn);",
  },
  FSQRT: {
    summary: "Fd = sqrt(Fn) (S or D form).",
    details: ["A negative operand gives NaN; the instruction never faults."],
    example: "fsqrt d1, d0",
    cExample: "Dd = sqrt(Dn);",
  },
  FCSEL: {
    summary: "Fd = cond ? Fn : Fm. The integer `CSEL` for the FP file.",
    details: [
      "The flags come from an earlier `FCMP` or `CMP`; `FCSEL` sets none of its own.",
      "The chosen register's bits are copied, so a NaN or a `-0.0` arrives untouched.",
    ],
    example: "fcsel d0, d1, d2, lt",
    cExample: "Fd = cond ? Fn : Fm;",
  },
  FCMP: {
    summary: "Set NZCV from Fn vs Fm (S or D form).",
    details: ["Unordered (NaN) sets C and V; `<` sets N; `==` sets Z."],
  },
  FCMPE: { summary: "Signaling FCMP; sets the same flags here (no FP exceptions are raised).", example: "fcmpe d0, d1", cExample: "// (a < b) etc. via NZCV" },
  FCVT: {
    summary: "Convert between the float views: `FCVT Dd, Sn` widens exactly, `FCVT Sd, Dn` narrows with rounding.",
    details: [
      "The step before printing a float: printf takes doubles, so widen with `fcvt d0, s0` first.",
    ],
    example: "fcvt d0, s0",
    cExample: "double d = (double)f;",
  },
  SCVTF: {
    summary: "Signed-int -> float (`SCVTF Dd, Xn` / `Dd, Wn` / `Sd, Wn`).",
    details: ["A third operand makes it fixed-point: `scvtf d0, x0, #2` divides by 4, so 6 gives 1.5."],
  },
  UCVTF: {
    summary: "Unsigned integer -> float (`UCVTF Dd, Xn` / `Sd, Wn`).",
    details: ["`SCVTF` reads the same bits as signed, so the two differ on every value with the top bit set."],
    example: "ucvtf d0, x0",
    cExample: "Fd = (double)(unsigned long)Rn;",
  },
  FCVTZS: {
    summary: "Float -> signed-int with truncation (`FCVTZS Wd, Dn` / `Wd, Sn`).",
    details: ["A third operand makes it fixed-point: `fcvtzs w0, d0, #2` multiplies by 4 before truncating, so 1.5 gives 6."],
  },
  FCVTNS: {
    summary: "Float -> signed integer, rounding to nearest with ties to even.",
    details: ["Ties go to the EVEN neighbour: 2.5 gives 2 and 3.5 gives 4. `FCVTZS` truncates toward zero instead."],
    example: "fcvtns w0, d0",
    cExample: "Rd = (int)nearbyint(Fn); // FE_TONEAREST",
  },
  FCVTNU: { summary: "Float -> unsigned integer, ties to even. Negatives saturate to 0.", example: "fcvtnu w0, d0" },
  FCVTZU: { summary: "Float -> unsigned integer, truncating toward zero. Negatives saturate to 0.", example: "fcvtzu w0, d0" },
  FCVTAS: {
    summary: "Float -> signed integer, rounding to nearest with ties AWAY from zero.",
    details: ["The other nearest mode: 2.5 gives 3 and -2.5 gives -3, where `FCVTNS` gives 2 and -2."],
    example: "fcvtas w0, d0",
    cExample: "Rd = (int)round(Fn);",
  },
  FCVTAU: { summary: "Float -> unsigned integer, ties away from zero.", example: "fcvtau w0, d0" },
  FCVTMS: { summary: "Float -> signed integer, rounding toward minus infinity (floor).", example: "fcvtms w0, d0", cExample: "Rd = (int)floor(Fn);" },
  FCVTMU: { summary: "Float -> unsigned integer, floor. Negatives saturate to 0.", example: "fcvtmu w0, d0" },
  FCVTPS: { summary: "Float -> signed integer, rounding toward plus infinity (ceiling).", example: "fcvtps w0, d0", cExample: "Rd = (int)ceil(Fn);" },
  FCVTPU: { summary: "Float -> unsigned integer, ceiling.", example: "fcvtpu w0, d0" },
  // the unscaled and no-allocate spellings (SIMD&FP registers only)
  LDUR: {
    summary: "Unscaled signed-offset load into a SIMD&FP register.",
    details: [
      "`imm` runs [-256, 255] and is never scaled by the access width.",
      "`LDR` picks this encoding on its own for a negative or unaligned offset, exactly as GAS does.",
    ],
    example: "ldur d3, [sp, 4]",
  },
  STUR: { summary: "Unscaled signed-offset store from a SIMD&FP register.", example: "stur d1, [sp, 4]" },
  LDNP: {
    summary: "No-allocate pair load: a plain signed offset, no writeback.",
    details: ["Identical here to `LDP`; on hardware it differs only in a cache hint."],
    example: "ldnp d3, d4, [sp]",
  },
  STNP: { summary: "No-allocate pair store, the counterpart of `LDNP`.", example: "stnp d1, d2, [sp]" },
  // advanced simd: moves and immediates
  MOVI: { summary: "Put an immediate in every lane.", example: "movi v3.16b, #0x55" },
  MVNI: { summary: "The same immediate, inverted.", example: "mvni v3.4h, #0x55" },
  DUP: { summary: "One value into every lane, from a general register or from one lane.", example: "dup v3.8b, w7" },
  INS: { summary: "Write one lane and leave the others alone.", example: "ins v3.b[15], w7" },
  UMOV: { summary: "One lane out into a general register, zero-extended.", example: "umov w3, v7.b[15]" },
  SMOV: { summary: "The same, sign-extended, so the lane has to be narrower than the register.", example: "smov w3, v7.b[15]" },
  // advanced simd: three-same
  MLA: { summary: "`Vd = Vd + Vn * Vm`: the destination is read as well as written.", example: "mla v3.8b, v7.8b, v21.8b" },
  MLS: { summary: "`Vd = Vd - Vn * Vm`.", example: "mls v3.8b, v7.8b, v21.8b" },
  PMUL: { summary: "Carry-less (polynomial) multiply of bytes: the partial products are XORed, not added, so there is no carry between bit positions.", example: "pmul v3.8b, v7.8b, v21.8b" },
  BSL: { summary: "Bitwise select, and the DESTINATION is the mask: each bit takes `Vn` where `Vd` holds 1 and `Vm` where it holds 0.", example: "bsl v3.8b, v7.8b, v21.8b" },
  BIT: { summary: "Insert if true: the destination keeps its bit where `Vm` is 0 and takes `Vn`'s where `Vm` is 1.", example: "bit v3.8b, v7.8b, v21.8b" },
  BIF: { summary: "Insert if false: the same with the mask inverted.", example: "bif v3.8b, v7.8b, v21.8b" },
  NOT: { summary: "The same word as `MVN`; objdump prints it back as `MVN`.", example: "not v3.8b, v7.8b" },
  // advanced simd: compares
  CMEQ: { summary: "Equal.", example: "cmeq v3.8b, v7.8b, v21.8b" },
  CMGT: { summary: "SIGNED greater than.", example: "cmgt v3.8b, v7.8b, v21.8b" },
  CMGE: { summary: "SIGNED greater or equal.", example: "cmge v3.8b, v7.8b, v21.8b" },
  CMHI: { summary: "UNSIGNED greater than.", example: "cmhi v3.8b, v7.8b, v21.8b" },
  CMHS: { summary: "UNSIGNED greater or equal.", example: "cmhs v3.8b, v7.8b, v21.8b" },
  CMLE: { summary: "Signed, against zero.", example: "cmle v3.8b, v7.8b, #0" },
  CMLT: { summary: "Signed, against zero; swap and use `CMGT`.", example: "cmlt v3.8b, v7.8b, #0" },
  CMTST: { summary: "Not a magnitude test at all: the lane holds ones when `Vn AND Vm` is non-zero.", example: "cmtst v3.8b, v7.8b, v21.8b" },
  // advanced simd: saturating and halving
  SQADD: { summary: "Signed saturating add: clamps to the lane's signed range.", example: "sqadd v3.8b, v7.8b, v21.8b" },
  UQADD: { summary: "Unsigned saturating add.", example: "uqadd v3.8b, v7.8b, v21.8b" },
  SQSUB: { summary: "Signed saturating subtract.", example: "sqsub v3.8b, v7.8b, v21.8b" },
  UQSUB: { summary: "Unsigned saturating subtract; a negative result clamps to zero.", example: "uqsub v3.8b, v7.8b, v21.8b" },
  SUQADD: { summary: "Accumulate an UNSIGNED source into a SIGNED destination and saturate as signed.", example: "suqadd v3.8b, v7.8b" },
  USQADD: { summary: "The other way round: a signed source into an unsigned destination, saturating as unsigned, so a negative source clamps at zero.", example: "usqadd v3.8b, v7.8b" },
  SQABS: { summary: "Saturating absolute value: `sqabs` of the minimum lane value gives the maximum (`-128` becomes `127`), where plain `ABS` wraps back to `-128`.", example: "sqabs v3.8b, v7.8b" },
  SQNEG: { summary: "Saturating negate, with the same edge.", example: "sqneg v3.8b, v7.8b" },
  SHADD: { summary: "Signed halving add: `(Vn + Vm) >> 1` computed at `esize + 1` bits.", example: "shadd v3.8b, v7.8b, v21.8b" },
  UHADD: { summary: "Unsigned halving add.", example: "uhadd v3.8b, v7.8b, v21.8b" },
  SRHADD: { summary: "Rounding halving add: 1 is added before the shift.", example: "srhadd v3.8b, v7.8b, v21.8b" },
  URHADD: { summary: "The unsigned rounding halving add.", example: "urhadd v3.8b, v7.8b, v21.8b" },
  SHSUB: { summary: "Signed halving subtract, the same extra bit.", example: "shsub v3.8b, v7.8b, v21.8b" },
  UHSUB: { summary: "Unsigned halving subtract.", example: "uhsub v3.8b, v7.8b, v21.8b" },
  SQDMULH: { summary: "Saturating doubling multiply, high half: `(2 * Vn * Vm) >> esize`.", example: "sqdmulh v3.4h, v7.4h, v21.4h" },
  SQRDMULH: { summary: "The rounding form: half an ulp is added before the shift.", example: "sqrdmulh v3.4h, v7.4h, v21.4h" },
  // advanced simd: max, min and across lanes
  SMAX: { summary: "Signed larger of each lane pair.", example: "smax v3.8b, v7.8b, v21.8b" },
  SMIN: { summary: "Signed smaller.", example: "smin v3.8b, v7.8b, v21.8b" },
  UMAX: { summary: "Unsigned larger.", example: "umax v3.8b, v7.8b, v21.8b" },
  UMIN: { summary: "Unsigned smaller.", example: "umin v3.8b, v7.8b, v21.8b" },
  SMAXP: { summary: "The pairwise `SMAX`.", example: "smaxp v3.8b, v7.8b, v21.8b" },
  SMINP: { summary: "The pairwise `SMIN`.", example: "sminp v3.8b, v7.8b, v21.8b" },
  UMAXP: { summary: "The pairwise `UMAX`.", example: "umaxp v3.8b, v7.8b, v21.8b" },
  UMINP: { summary: "The pairwise `UMIN`.", example: "uminp v3.8b, v7.8b, v21.8b" },
  ADDP: { summary: "The pairwise add.", example: "addp v3.8b, v7.8b, v21.8b" },
  ADDV: { summary: "Sum of every lane, truncated to the lane's own width.", example: "addv b3, v7.8b" },
  SADDLV: { summary: "Widen each lane to twice its width, THEN sum, so the total cannot overflow the source lane.", example: "saddlv h3, v7.8b" },
  UADDLV: { summary: "The unsigned widening sum.", example: "uaddlv h3, v7.8b" },
  SMAXV: { summary: "Largest signed lane of the whole vector.", example: "smaxv b3, v7.8b" },
  SMINV: { summary: "Smallest signed lane.", example: "sminv b3, v7.8b" },
  UMAXV: { summary: "Largest unsigned lane.", example: "umaxv b3, v7.8b" },
  UMINV: { summary: "Smallest unsigned lane.", example: "uminv b3, v7.8b" },
  SADDLP: { summary: "Pairwise widening add: each pair of source lanes becomes one destination lane of twice the width, signed.", example: "saddlp v3.4h, v7.8b" },
  UADDLP: { summary: "The unsigned pairwise widening add.", example: "uaddlp v3.4h, v7.8b" },
  SADALP: { summary: "The same sum ACCUMULATED into what the destination already holds.", example: "sadalp v3.4h, v7.8b" },
  UADALP: { summary: "The unsigned accumulating form.", example: "uadalp v3.4h, v7.8b" },
  // advanced simd: absolute differences
  SABD: { summary: "Absolute difference, both lanes read as signed.", example: "sabd v3.8b, v7.8b, v21.8b" },
  UABD: { summary: "Absolute difference, both read as unsigned.", example: "uabd v3.8b, v7.8b, v21.8b" },
  SABA: { summary: "The signed absolute difference ACCUMULATED into the destination.", example: "saba v3.8b, v7.8b, v21.8b" },
  UABA: { summary: "The unsigned one, accumulated.", example: "uaba v3.8b, v7.8b, v21.8b" },
  // advanced simd: two-register misc
  ABS: { summary: "Absolute value, WRAPPING at the lane's width: the minimum value is its own absolute value.", example: "abs v3.8b, v7.8b" },
  CNT: { summary: "Population count, per BYTE.", example: "cnt v3.8b, v7.8b" },
  REV64: { summary: "The same inside each 64-bit container.", example: "rev64 v3.8b, v7.8b" },
  URECPE: { summary: "The unsigned fixed-point reciprocal ESTIMATE, read out of the architecture's table rather than computed.", example: "urecpe v3.2s, v7.2s" },
  URSQRTE: { summary: "The reciprocal square-root estimate from the same kind of table, with the cut at 0.25 (top two bits clear).", example: "ursqrte v3.2s, v7.2s" },
  // advanced simd: widening, narrowing and doubling
  SADDL: { summary: "Sign-extend both lanes to twice their width, THEN add, so the sum cannot overflow the destination.", example: "saddl v3.8h, v7.8b, v21.8b" },
  SADDL2: { summary: "The same over the upper half of the sources.", example: "saddl2 v3.8h, v7.16b, v21.16b" },
  UADDL: { summary: "Zero-extend instead: the `S`/`U` pair differ in nothing else.", example: "uaddl v3.8h, v7.8b, v21.8b" },
  UADDL2: { summary: "The unsigned upper-half form.", example: "uaddl2 v3.8h, v7.16b, v21.16b" },
  SSUBL: { summary: "Extend, then subtract.", example: "ssubl v3.8h, v7.8b, v21.8b" },
  SSUBL2: { summary: "The upper-half form.", example: "ssubl2 v3.8h, v7.16b, v21.16b" },
  USUBL: { summary: "The unsigned widening subtract.", example: "usubl v3.8h, v7.8b, v21.8b" },
  USUBL2: { summary: "The unsigned upper-half form.", example: "usubl2 v3.8h, v7.16b, v21.16b" },
  SADDW: { summary: "Only the SECOND source is narrow: it is extended and added to a first source already at the destination's width.", example: "saddw v3.8h, v7.8h, v21.8b" },
  SADDW2: { summary: "The upper half of the narrow source.", example: "saddw2 v3.8h, v7.8h, v21.16b" },
  UADDW: { summary: "Zero-extending.", example: "uaddw v3.8h, v7.8h, v21.8b" },
  UADDW2: { summary: "The unsigned upper-half form.", example: "uaddw2 v3.8h, v7.8h, v21.16b" },
  SSUBW: { summary: "Extend the narrow source, then subtract it.", example: "ssubw v3.8h, v7.8h, v21.8b" },
  SSUBW2: { summary: "The upper-half form.", example: "ssubw2 v3.8h, v7.8h, v21.16b" },
  USUBW: { summary: "The unsigned widening subtract.", example: "usubw v3.8h, v7.8h, v21.8b" },
  USUBW2: { summary: "The unsigned upper-half form.", example: "usubw2 v3.8h, v7.8h, v21.16b" },
  SMULL2: { summary: "The widening product over the upper half.", example: "smull2 v3.8h, v7.16b, v21.16b" },
  UMULL2: { summary: "The unsigned one; plain `UMULL` shares its arm the same way.", example: "umull2 v3.8h, v7.16b, v21.16b" },
  SMLAL: { summary: "The widening product ACCUMULATED: the destination is read as well as written.", example: "smlal v3.8h, v7.8b, v21.8b" },
  SMLAL2: { summary: "The upper-half form.", example: "smlal2 v3.8h, v7.16b, v21.16b" },
  UMLAL: { summary: "The unsigned accumulating product.", example: "umlal v3.8h, v7.8b, v21.8b" },
  UMLAL2: { summary: "The unsigned upper-half form.", example: "umlal2 v3.8h, v7.16b, v21.16b" },
  SMLSL: { summary: "The widening product SUBTRACTED from the destination.", example: "smlsl v3.8h, v7.8b, v21.8b" },
  SMLSL2: { summary: "The upper-half form.", example: "smlsl2 v3.8h, v7.16b, v21.16b" },
  UMLSL: { summary: "The unsigned subtracting form.", example: "umlsl v3.8h, v7.8b, v21.8b" },
  UMLSL2: { summary: "The unsigned upper-half form.", example: "umlsl2 v3.8h, v7.16b, v21.16b" },
  SABDL: { summary: "Widening absolute difference: extend both lanes, subtract, take the magnitude, so nothing wraps the way the same-width `SABD` can.", example: "sabdl v3.8h, v7.8b, v21.8b" },
  SABDL2: { summary: "The upper-half form.", example: "sabdl2 v3.8h, v7.16b, v21.16b" },
  UABDL: { summary: "Both lanes read unsigned.", example: "uabdl v3.8h, v7.8b, v21.8b" },
  UABDL2: { summary: "The unsigned upper-half form.", example: "uabdl2 v3.8h, v7.16b, v21.16b" },
  SABAL: { summary: "The same difference accumulated into the destination.", example: "sabal v3.8h, v7.8b, v21.8b" },
  SABAL2: { summary: "The upper-half form.", example: "sabal2 v3.8h, v7.16b, v21.16b" },
  UABAL: { summary: "The unsigned accumulating difference.", example: "uabal v3.8h, v7.8b, v21.8b" },
  UABAL2: { summary: "The unsigned upper-half form.", example: "uabal2 v3.8h, v7.16b, v21.16b" },
  ADDHN: { summary: "Add at the SOURCE width and keep the HIGH half of each sum; the low half is discarded.", example: "addhn v3.8b, v7.8h, v21.8h" },
  ADDHN2: { summary: "The same sums written into the UPPER half of the destination, the low half untouched.", example: "addhn2 v3.16b, v7.8h, v21.8h" },
  RADDHN: { summary: "Rounding: half an ulp of the kept half (bit `esize - 1` of the sum) is added before the top half is taken.", example: "raddhn v3.8b, v7.8h, v21.8h" },
  RADDHN2: { summary: "The rounding upper-half form.", example: "raddhn2 v3.16b, v7.8h, v21.8h" },
  SUBHN: { summary: "The difference's high half.", example: "subhn v3.8b, v7.8h, v21.8h" },
  SUBHN2: { summary: "The upper-half form.", example: "subhn2 v3.16b, v7.8h, v21.8h" },
  RSUBHN: { summary: "The rounding difference.", example: "rsubhn v3.8b, v7.8h, v21.8h" },
  RSUBHN2: { summary: "The rounding upper-half form.", example: "rsubhn2 v3.16b, v7.8h, v21.8h" },
  SQDMULL: { summary: "Doubled widening product, saturating.", example: "sqdmull v3.4s, v7.4h, v21.4h" },
  SQDMULL2: { summary: "The upper-half form; no scalar spelling, since a scalar has no halves.", example: "sqdmull2 v3.4s, v7.8h, v21.8h" },
  SQDMLAL: { summary: "The doubled product accumulated.", example: "sqdmlal v3.4s, v7.4h, v21.4h" },
  SQDMLAL2: { summary: "The upper-half accumulating form.", example: "sqdmlal2 v3.4s, v7.8h, v21.8h" },
  SQDMLSL: { summary: "The doubled product subtracted, saturating at both steps.", example: "sqdmlsl v3.4s, v7.4h, v21.4h" },
  SQDMLSL2: { summary: "The upper-half subtracting form.", example: "sqdmlsl2 v3.4s, v7.8h, v21.8h" },
  PMULL: { summary: "Carry-less (polynomial) widening multiply of bytes: the partial products are XORed rather than added, so nothing carries between bit positions and the whole product fits the halfword.", example: "pmull v3.8h, v7.8b, v21.8b" },
  PMULL2: { summary: "The same over the upper eight bytes.", example: "pmull2 v3.8h, v7.16b, v21.16b" },
  XTN: { summary: "Truncate each lane to half its width; whatever does not fit is discarded.", example: "xtn v3.8b, v7.8h" },
  XTN2: { summary: "The same results in the UPPER half of the destination.", example: "xtn2 v3.16b, v7.8h" },
  SQXTN: { summary: "Signed saturating narrow: a lane past the narrow signed range clamps to it instead of losing its top bits.", example: "sqxtn v3.8b, v7.8h" },
  SQXTN2: { summary: "The upper-half form.", example: "sqxtn2 v3.16b, v7.8h" },
  UQXTN: { summary: "Unsigned saturating narrow.", example: "uqxtn v3.8b, v7.8h" },
  UQXTN2: { summary: "The unsigned upper-half form.", example: "uqxtn2 v3.16b, v7.8h" },
  SQXTUN: { summary: "The mixed one: the source is read SIGNED and saturated into an UNSIGNED lane, so a negative source clamps at zero and a large positive one at all ones.", example: "sqxtun v3.8b, v7.8h" },
  SQXTUN2: { summary: "The mixed upper-half form.", example: "sqxtun2 v3.16b, v7.8h" },
  SHLL: { summary: "Shift each lane left by exactly its own width into a lane of twice that, so the source lands in the top half of the result with zeros below it.", example: "shll v3.8h, v7.8b, #8" },
  SHLL2: { summary: "The same over the upper half of the source.", example: "shll2 v3.8h, v7.16b, #8" },
  // advanced simd: shifts
  SHL: { summary: "Shift left, discarding what leaves the lane.", example: "shl v3.8b, v7.8b, #5" },
  SSHR: { summary: "Arithmetic (sign-filling) shift right; at `#esize` every lane is all zeros or all ones.", example: "sshr v3.8b, v7.8b, #5" },
  USHR: { summary: "Logical shift right; at `#esize` the lane is zero.", example: "ushr v3.8b, v7.8b, #5" },
  SSRA: { summary: "The signed shift ACCUMULATED: `Vd = Vd + (Vn >> shift)`, wrapping at the lane.", example: "ssra v3.8b, v7.8b, #5" },
  USRA: { summary: "The unsigned shift, accumulated.", example: "usra v3.8b, v7.8b, #5" },
  SRSHR: { summary: "Rounding signed shift: `1 << (shift - 1)` is added before the shift.", example: "srshr v3.8b, v7.8b, #5" },
  URSHR: { summary: "The unsigned rounding shift.", example: "urshr v3.8b, v7.8b, #5" },
  SRSRA: { summary: "The rounding signed shift, accumulated.", example: "srsra v3.8b, v7.8b, #5" },
  URSRA: { summary: "The rounding unsigned shift, accumulated.", example: "ursra v3.8b, v7.8b, #5" },
  SLI: { summary: "Shift left and INSERT: the destination's low `shift` bits survive instead of being shifted in as zeros.", example: "sli v3.8b, v7.8b, #5" },
  SRI: { summary: "Shift right and insert: the destination's high `shift` bits survive.", example: "sri v3.8b, v7.8b, #5" },
  SQSHL: { summary: "Signed saturating shift left: what would leave the lane clamps to the lane's limit instead.", example: "sqshl v3.8b, v7.8b, #5" },
  UQSHL: { summary: "Unsigned saturating shift left.", example: "uqshl v3.8b, v7.8b, #5" },
  SQSHLU: { summary: "The mixed one: the lane is read SIGNED and saturated into an UNSIGNED result, so a negative lane answers zero.", example: "sqshlu v3.8b, v7.8b, #5" },
  SSHLL: { summary: "Sign-extend to twice the width, THEN shift left, so nothing can leave the result lane.", example: "sshll v3.8h, v7.8b, #3" },
  SSHLL2: { summary: "The same over the upper half of the source.", example: "sshll2 v3.8h, v7.16b, #3" },
  USHLL: { summary: "Zero-extending.", example: "ushll v3.8h, v7.8b, #3" },
  USHLL2: { summary: "The unsigned upper-half form.", example: "ushll2 v3.8h, v7.16b, #3" },
  SXTL: { summary: "The alias for `SSHLL ..., #0`: the same word, and the spelling objdump prints back for it.", example: "sxtl v3.8h, v7.8b" },
  SXTL2: { summary: "The upper-half form, alias of `SSHLL2 ..., #0`.", example: "sxtl2 v3.8h, v7.16b" },
  UXTL: { summary: "The zero-extending alias of `USHLL ..., #0`.", example: "uxtl v3.8h, v7.8b" },
  UXTL2: { summary: "The upper-half zero-extending alias.", example: "uxtl2 v3.8h, v7.16b" },
  SHRN: { summary: "Shift each source lane right, then truncate into a lane of half the width.", example: "shrn v3.8b, v7.8h, #3" },
  SHRN2: { summary: "The results in the UPPER half of the destination, the low half untouched.", example: "shrn2 v3.16b, v7.8h, #3" },
  RSHRN: { summary: "Rounding: half an ulp is added before the shift.", example: "rshrn v3.8b, v7.8h, #3" },
  RSHRN2: { summary: "The rounding upper-half form.", example: "rshrn2 v3.16b, v7.8h, #3" },
  SQSHRN: { summary: "Signed saturating narrowing shift: the shift happens at the source width and the clamp at the destination's.", example: "sqshrn v3.8b, v7.8h, #3" },
  SQSHRN2: { summary: "The upper-half form; no `2` form has a scalar spelling.", example: "sqshrn2 v3.16b, v7.8h, #3" },
  UQSHRN: { summary: "Unsigned saturating narrowing shift.", example: "uqshrn v3.8b, v7.8h, #3" },
  UQSHRN2: { summary: "The unsigned upper-half form.", example: "uqshrn2 v3.16b, v7.8h, #3" },
  SQRSHRN: { summary: "The signed rounding one: half an ulp before the shift, then the clamp.", example: "sqrshrn v3.8b, v7.8h, #3" },
  SQRSHRN2: { summary: "The rounding upper-half form.", example: "sqrshrn2 v3.16b, v7.8h, #3" },
  UQRSHRN: { summary: "The unsigned rounding narrowing shift.", example: "uqrshrn v3.8b, v7.8h, #3" },
  UQRSHRN2: { summary: "The unsigned rounding upper-half form.", example: "uqrshrn2 v3.16b, v7.8h, #3" },
  SQSHRUN: { summary: "Signed source, UNSIGNED saturating result: a negative source clamps at zero.", example: "sqshrun v3.8b, v7.8h, #3" },
  SQSHRUN2: { summary: "The upper-half form.", example: "sqshrun2 v3.16b, v7.8h, #3" },
  SQRSHRUN: { summary: "The rounding mixed form.", example: "sqrshrun v3.8b, v7.8h, #3" },
  SQRSHRUN2: { summary: "The rounding mixed upper-half form.", example: "sqrshrun2 v3.16b, v7.8h, #3" },
  SSHL: { summary: "Signed shift by the per-lane count; a right shift fills with the sign bit.", example: "sshl v3.8b, v7.8b, v21.8b" },
  USHL: { summary: "Unsigned: a right shift fills with zeros.", example: "ushl v3.8b, v7.8b, v21.8b" },
  SRSHL: { summary: "Rounding: on a right shift, half an ulp of the discarded bits is added first.", example: "srshl v3.8b, v7.8b, v21.8b" },
  URSHL: { summary: "The unsigned rounding form.", example: "urshl v3.8b, v7.8b, v21.8b" },
  SQRSHL: { summary: "Signed saturating rounding shift.", example: "sqrshl v3.8b, v7.8b, v21.8b" },
  UQRSHL: { summary: "The unsigned saturating rounding shift.", example: "uqrshl v3.8b, v7.8b, v21.8b" },
  // advanced simd: permutes and table lookups
  EXT: { summary: "`Vn` and `Vm` laid end to end, read from byte `#index` on for as many bytes as the arrangement holds.", example: "ext v3.16b, v7.16b, v21.16b, #11" },
  TBL: { summary: "Each byte of `Vm` indexes a byte table made of consecutive registers from `Vn` on.", example: "tbl v3.8b, {v7.16b, v8.16b}, v21.8b" },
  TBX: { summary: "The same lookup, except an out-of-range index LEAVES the destination byte alone instead of zeroing it.", example: "tbx v3.8b, {v7.16b}, v21.8b" },
  ZIP1: { summary: "Interleave the LOW halves of the two sources, `Vn` lane first.", example: "zip1 v3.16b, v7.16b, v21.16b" },
  ZIP2: { summary: "The same over the UPPER halves.", example: "zip2 v3.16b, v7.16b, v21.16b" },
  UZP1: { summary: "Every EVEN lane of `Vn` then `Vm`, laid end to end: the de-interleave `ZIP1` undoes.", example: "uzp1 v3.16b, v7.16b, v21.16b" },
  UZP2: { summary: "Every ODD lane of the two.", example: "uzp2 v3.16b, v7.16b, v21.16b" },
  TRN1: { summary: "The even lanes of both, alternating: `Vd[2i] = Vn[2i]`, `Vd[2i+1] = Vm[2i]`.", example: "trn1 v3.16b, v7.16b, v21.16b" },
  TRN2: { summary: "The odd lanes of both, the other half of a 2x2 transpose.", example: "trn2 v3.16b, v7.16b, v21.16b" },
  // advanced simd: floating-point three-same and pairwise
  FMLA: { summary: "Fused multiply-add into the destination: `Vd = Vd + Vn * Vm`, one rounding over the whole thing.", example: "fmla v3.2s, v7.2s, v21.2s" },
  FMLS: { summary: "`Vd = Vd - Vn * Vm`.", example: "fmls v3.2s, v7.2s, v21.2s" },
  FMULX: { summary: "The product, except that an infinity against a zero answers exactly `2.0` with the sign of the product, where `FMUL` answers with the default NaN.", example: "fmulx v3.2s, v7.2s, v21.2s" },
  FABD: { summary: "`|Vn - Vm|`.", example: "fabd v3.2s, v7.2s, v21.2s" },
  FRECPS: { summary: "The Newton-Raphson step for a reciprocal: `2.0 - Vn * Vm`, fused.", example: "frecps v3.2s, v7.2s, v21.2s" },
  FRSQRTS: { summary: "The step for a reciprocal square root: `(3.0 - Vn * Vm) / 2`.", example: "frsqrts v3.2s, v7.2s, v21.2s" },
  FADDP: { summary: "Pairwise: `Vn`'s lanes then `Vm`'s, folded two at a time, so the low half of the destination comes from `Vn`.", example: "faddp v3.2s, v7.2s, v21.2s" },
  FMAXP: { summary: "The pairwise maximum, with `FMAX`'s NaN rule.", example: "fmaxp v3.2s, v7.2s, v21.2s" },
  FMINP: { summary: "The pairwise minimum.", example: "fminp v3.2s, v7.2s, v21.2s" },
  FMAXNMP: { summary: "The pairwise `FMAXNM`.", example: "fmaxnmp v3.2s, v7.2s, v21.2s" },
  FMINNMP: { summary: "The pairwise `FMINNM`.", example: "fminnmp v3.2s, v7.2s, v21.2s" },
  FMAXV: { summary: "The whole vector folded to one scalar.", example: "fmaxv s3, v7.4s" },
  FMINV: { summary: "The minimum fold.", example: "fminv s3, v7.4s" },
  FMAXNMV: { summary: "The fold that ignores quiet NaNs.", example: "fmaxnmv s3, v7.4s" },
  FMINNMV: { summary: "The same for the minimum.", example: "fminnmv s3, v7.4s" },
  // advanced simd: floating-point unary
  FRECPE: { summary: "A reciprocal ESTIMATE, eight significant bits from the architecture's own table (the same table `URECPE` reads).", example: "frecpe v3.2s, v7.2s" },
  FRSQRTE: { summary: "A reciprocal-square-root estimate from the matching table.", example: "frsqrte v3.2s, v7.2s" },
  FRECPX: { summary: "Scalar only: the sign kept, the exponent complemented, the mantissa zeroed, which is the exact power of two a reciprocal lands on.", example: "frecpx s3, s7" },
  FRINTN: { summary: "Round to an integral float, nearest with ties to EVEN: `2.5` gives `2.0`.", example: "frintn v3.2s, v7.2s" },
  FRINTA: { summary: "Nearest with ties AWAY from zero: `2.5` gives `3.0`.", example: "frinta v3.2s, v7.2s" },
  FRINTM: { summary: "Toward minus infinity (floor).", example: "frintm v3.2s, v7.2s" },
  FRINTP: { summary: "Toward plus infinity (ceiling).", example: "frintp v3.2s, v7.2s" },
  FRINTZ: { summary: "Toward zero (truncate).", example: "frintz v3.2s, v7.2s" },
  FRINTX: { summary: "The current rounding mode, which here is nearest-even.", example: "frintx v3.2s, v7.2s" },
  FRINTI: { summary: "The current rounding mode, quietly.", example: "frinti v3.2s, v7.2s" },
  // advanced simd: floating-point compares
  FCMEQ: { summary: "All ones where the lanes are equal, all zeros where they are not.", example: "fcmeq v3.2s, v7.2s, v21.2s" },
  FCMGE: { summary: "Greater than or equal.", example: "fcmge v3.2s, v7.2s, v21.2s" },
  FCMGT: { summary: "Strictly greater than.", example: "fcmgt v3.2s, v7.2s, v21.2s" },
  FCMLE: { summary: "Less than or equal to zero.", example: "fcmle v3.2s, v7.2s, #0.0" },
  FCMLT: { summary: "Strictly less than zero, same story.", example: "fcmlt v3.2s, v7.2s, #0.0" },
  FACGE: { summary: "`FCMGE` on the absolute values, so the signs are ignored and `-3.0` beats `2.0`.", example: "facge v3.2s, v7.2s, v21.2s" },
  FACGT: { summary: "The strict absolute compare.", example: "facgt v3.2s, v7.2s, v21.2s" },
  // advanced simd: floating-point conversions
  FCVTN: { summary: "Narrow each lane to half its width, round to nearest even, into the LOW half of the destination (the upper half is zeroed).", example: "fcvtn v3.4h, v7.4s" },
  FCVTN2: { summary: "The same, into the UPPER half, leaving the low half alone.", example: "fcvtn2 v3.8h, v7.4s" },
  FCVTL: { summary: "Widen each lane, which is exact.", example: "fcvtl v3.4s, v7.4h" },
  FCVTL2: { summary: "The same, reading the UPPER half.", example: "fcvtl2 v3.4s, v7.8h" },
  FCVTXN: { summary: "Narrow `D` to `S` with round to ODD: toward zero, but an inexact result takes the neighbour with an odd significand, so a later widening can still tell the two halves of a tie apart.", example: "fcvtxn v3.2s, v7.2d" },
  FCVTXN2: { summary: "The upper-half form.", example: "fcvtxn2 v3.4s, v7.2d" },
  // advanced simd: structure loads and stores
  LD1: { summary: "Contiguous load, no interleaving.", example: "ld1 {v3.8b}, [x7]" },
  ST1: { summary: "The contiguous store.", example: "st1 {v3.16b}, [x7]" },
  LD2: { summary: "Two-way de-interleave: element 0 to the first register, element 1 to the second, alternating on.", example: "ld2 {v3.8b, v4.8b}, [x7]" },
  ST2: { summary: "The two-way interleave, the exact inverse.", example: "st2 {v3.8b, v4.8b}, [x7]" },
  LD3: { summary: "Three-way de-interleave, for `xyz` triples.", example: "ld3 {v3.8b, v4.8b, v5.8b}, [x7]" },
  ST3: { summary: "The three-way interleave.", example: "st3 {v3.8b, v4.8b, v5.8b}, [x7]" },
  LD4: { summary: "Four-way de-interleave, for `rgba` quads.", example: "ld4 {v4.8b, v5.8b, v6.8b, v7.8b}, [x7]" },
  ST4: { summary: "The four-way interleave.", example: "st4 {v3.8b, v4.8b, v5.8b, v6.8b}, [x7]" },
  LD1R: { summary: "One element filling every lane.", example: "ld1r {v3.16b}, [x7]" },
  LD2R: { summary: "Two consecutive elements, one broadcast into each register.", example: "ld2r {v3.8b, v4.8b}, [x7]" },
  LD3R: { summary: "Three elements, one per register.", example: "ld3r {v3.8b, v4.8b, v5.8b}, [x7]" },
  LD4R: { summary: "Four elements, one per register.", example: "ld4r {v4.8b, v5.8b, v6.8b, v7.8b}, [x7]" },
};

/** Case-insensitive lookup; condition variants collapse to B.COND. */
export function lookupDoc(raw: string): InstructionDoc | undefined {
  const key = raw.toUpperCase();
  if (key.startsWith("B.") && key !== "B.COND") return INSTRUCTION_DOCS["B.COND"];
  return INSTRUCTION_DOCS[key];
}
