/**
 * Every mnemonic the assembler accepts, lowercase, in instruction-reference
 * order. The names live apart from the hover-card prose so the landing page's
 * highlighter does not pull that table into its bundle; mnemonics.test.ts
 * keeps the two lists equal. The `b.<cond>` branches are left out because the
 * table folds them into one `B.COND` entry and both highlighters match them.
 */
export const ARM64_MNEMONIC_NAMES: readonly string[] = [
  "mov", "movz", "movk", "movn", "add", "adds", "sub", "subs", "ccmp",
  "ccmn", "smaddl", "smsubl", "umaddl", "umsubl", "smnegl", "umnegl", "clz",
  "cls", "rbit", "rev", "rev16", "rev32", "adc", "adcs", "sbc", "sbcs",
  "and", "ands", "orr", "eor", "bic", "lsl", "lsr", "asr", "ror", "extr", "sbfx",
  "ubfx", "bfi", "bfxil", "ubfiz", "sbfiz", "sxtb", "sxth", "sxtw", "uxtb",
  "uxth", "uxtw", "mul", "madd", "msub", "mneg", "smull", "umull", "smulh",
  "umulh", "udiv", "sdiv", "neg", "negs", "mvn", "orn", "eon", "cmp", "cmn",
  "tst", "csel", "csinc", "csinv", "csneg", "cset", "csetm", "cinc", "cinv",
  "cneg", "ldr", "str", "ldrb", "strb", "ldrh", "strh", "ldrsb", "ldrsh",
  "ldrsw", "ldpsw", "ldp", "stp", "adr", "adrp", "b", "bl", "br", "blr", "ret", "cbz",
  "cbnz", "tbz", "tbnz", "svc", "brk", "nop", "fmov", "fadd", "fsub", "fmul",
  "fdiv", "fnmul", "fmadd", "fmsub", "fnmadd", "fnmsub", "fmax", "fmin",
  "fmaxnm", "fminnm", "fneg", "fabs", "fsqrt", "fcsel", "fcmp", "fcmpe", "fccmp", "fccmpe",
  "fcvt", "scvtf", "ucvtf", "fcvtzs", "fcvtns", "fcvtnu", "fcvtzu", "fcvtas",
  "fcvtau", "fcvtms", "fcvtmu", "fcvtps", "fcvtpu", "ldur", "stur", "ldnp",
  "stnp", "movi", "mvni", "dup", "ins", "umov", "smov", "mla", "mls", "pmul",
  "bsl", "bit", "bif", "not", "cmeq", "cmgt", "cmge", "cmhi", "cmhs", "cmle",
  "cmlt", "cmtst", "sqadd", "uqadd", "sqsub", "uqsub", "suqadd", "usqadd",
  "sqabs", "sqneg", "shadd", "uhadd", "srhadd", "urhadd", "shsub", "uhsub",
  "sqdmulh", "sqrdmulh", "smax", "smin", "umax", "umin", "smaxp", "sminp",
  "umaxp", "uminp", "addp", "addv", "saddlv", "uaddlv", "smaxv", "sminv",
  "umaxv", "uminv", "saddlp", "uaddlp", "sadalp", "uadalp", "sabd", "uabd",
  "saba", "uaba", "abs", "cnt", "rev64", "urecpe", "ursqrte", "saddl",
  "saddl2", "uaddl", "uaddl2", "ssubl", "ssubl2", "usubl", "usubl2", "saddw",
  "saddw2", "uaddw", "uaddw2", "ssubw", "ssubw2", "usubw", "usubw2",
  "smull2", "umull2", "smlal", "smlal2", "umlal", "umlal2", "smlsl",
  "smlsl2", "umlsl", "umlsl2", "sabdl", "sabdl2", "uabdl", "uabdl2", "sabal",
  "sabal2", "uabal", "uabal2", "addhn", "addhn2", "raddhn", "raddhn2",
  "subhn", "subhn2", "rsubhn", "rsubhn2", "sqdmull", "sqdmull2", "sqdmlal",
  "sqdmlal2", "sqdmlsl", "sqdmlsl2", "pmull", "pmull2", "xtn", "xtn2",
  "sqxtn", "sqxtn2", "uqxtn", "uqxtn2", "sqxtun", "sqxtun2", "shll", "shll2",
  "shl", "sshr", "ushr", "ssra", "usra", "srshr", "urshr", "srsra", "ursra",
  "sli", "sri", "sqshl", "uqshl", "sqshlu", "sshll", "sshll2", "ushll",
  "ushll2", "sxtl", "sxtl2", "uxtl", "uxtl2", "shrn", "shrn2", "rshrn",
  "rshrn2", "sqshrn", "sqshrn2", "uqshrn", "uqshrn2", "sqrshrn", "sqrshrn2",
  "uqrshrn", "uqrshrn2", "sqshrun", "sqshrun2", "sqrshrun", "sqrshrun2",
  "sshl", "ushl", "srshl", "urshl", "sqrshl", "uqrshl", "ext", "tbl", "tbx",
  "zip1", "zip2", "uzp1", "uzp2", "trn1", "trn2", "fmla", "fmls", "fmulx",
  "fabd", "frecps", "frsqrts", "faddp", "fmaxp", "fminp", "fmaxnmp",
  "fminnmp", "fmaxv", "fminv", "fmaxnmv", "fminnmv", "frecpe", "frsqrte",
  "frecpx", "frintn", "frinta", "frintm", "frintp", "frintz", "frintx",
  "frinti", "fcmeq", "fcmge", "fcmgt", "fcmle", "fcmlt", "facge", "facgt",
  "fcvtn", "fcvtn2", "fcvtl", "fcvtl2", "fcvtxn", "fcvtxn2", "ld1", "st1",
  "ld2", "st2", "ld3", "st3", "ld4", "st4", "ld1r", "ld2r", "ld3r", "ld4r",
];
