/**
 * Monaco's editor features, one loader each, in the order
 * monaco-editor/features/register.all imports them. The editor evaluates them
 * one task at a time (monaco-setup.ts says why). Keeping register.all's order means
 * the modules run exactly as that one import would run them, and its test
 * fails when a monaco upgrade changes the list.
 *
 * One feature is left out: inlineCompletions, the grey suggested text an
 * inline completion provider draws after the caret. This editor registers no
 * such provider, and it was by far the largest feature in the monaco chunk.
 */
export const MONACO_FEATURES: ReadonlyArray<() => Promise<unknown>> = [
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/anchorSelect/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/bracketMatching/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/caretOperations/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/clipboard/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/codeAction/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/codeEditor/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/codelens/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/codicon/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/colorPicker/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/comment/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/contextmenu/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/cursorUndo/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/diffEditor/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/diffEditorBreadcrumbs/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/dnd/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/documentSymbols/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/dropOrPasteInto/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/find/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/floatingMenu/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/folding/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/fontZoom/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/format/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/gotoError/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/gotoLine/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/gotoSymbol/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/gpu/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/hover/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/indentation/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/inlayHints/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/inlineProgress/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/inPlaceReplace/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/insertFinalNewLine/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/inspectTokens/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/iPadShowKeyboard/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/lineSelection/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/linesOperations/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/linkedEditing/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/links/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/longLinesHelper/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/middleScroll/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/multicursor/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/parameterHints/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/placeholderText/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/quickCommand/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/quickHelp/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/quickOutline/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/readOnlyMessage/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/referenceSearch/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/rename/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/sectionHeaders/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/semanticTokens/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/smartSelect/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/snippet/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/stickyScroll/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/suggest/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/toggleHighContrast/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/toggleTabFocusMode/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/tokenization/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/unicodeHighlighter/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/unusualLineTerminators/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/wordHighlighter/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/wordOperations/register"),
  () => import(/* webpackChunkName: "monaco" */ "monaco-editor/features/wordPartOperations/register"),
];
